// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package db

import (
	"context"
	"database/sql"
)

const getDailyViews = `-- name: GetDailyViews :many
SELECT
    strftime('%Y-%m-%d', substr(watched_at, 1, 26)) AS date,
    COUNT(*) AS view_count
FROM watched_history
WHERE substr(watched_at, 1, 26) >= ?
  AND substr(watched_at, 1, 26) < ?
  AND watched_at IS NOT NULL
GROUP BY strftime('%Y-%m-%d', substr(watched_at, 1, 26))
ORDER BY date DESC
`

type GetDailyViewsParams struct {
	WatchedAt   sql.NullTime
	WatchedAt_2 sql.NullTime
}

type GetDailyViewsRow struct {
	Date      interface{}
	ViewCount int64
}

func (q *Queries) GetDailyViews(ctx context.Context, arg GetDailyViewsParams) ([]GetDailyViewsRow, error) {
	rows, err := q.db.QueryContext(ctx, getDailyViews, arg.WatchedAt, arg.WatchedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDailyViewsRow
	for rows.Next() {
		var i GetDailyViewsRow
		if err := rows.Scan(&i.Date, &i.ViewCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDailyViewsWithDetails = `-- name: GetDailyViewsWithDetails :many
SELECT
    strftime('%Y-%m-%d', substr(wh.watched_at, 1, 26)) AS date,
    COUNT(*) AS view_count,
    wh.id,
    v.file_name,
    v.subtitle,
    COALESCE(s.syobocal_title_name, 'No Series') AS series_name
FROM watched_history wh
LEFT JOIN video v ON wh.video_id = v.id
LEFT JOIN series s ON v.series_id = s.id
WHERE substr(wh.watched_at, 1, 26) >= ?
  AND substr(wh.watched_at, 1, 26) < ?
  AND wh.watched_at IS NOT NULL
GROUP BY strftime('%Y-%m-%d', substr(wh.watched_at, 1, 26)), wh.video_id, v.file_name, s.syobocal_title_name
ORDER BY date DESC, wh.video_id DESC
`

type GetDailyViewsWithDetailsParams struct {
	WatchedAt   sql.NullTime
	WatchedAt_2 sql.NullTime
}

type GetDailyViewsWithDetailsRow struct {
	Date       interface{}
	ViewCount  int64
	ID         int64
	FileName   sql.NullString
	Subtitle   sql.NullString
	SeriesName string
}

func (q *Queries) GetDailyViewsWithDetails(ctx context.Context, arg GetDailyViewsWithDetailsParams) ([]GetDailyViewsWithDetailsRow, error) {
	rows, err := q.db.QueryContext(ctx, getDailyViewsWithDetails, arg.WatchedAt, arg.WatchedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDailyViewsWithDetailsRow
	for rows.Next() {
		var i GetDailyViewsWithDetailsRow
		if err := rows.Scan(
			&i.Date,
			&i.ViewCount,
			&i.ID,
			&i.FileName,
			&i.Subtitle,
			&i.SeriesName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMonthlyStats = `-- name: GetMonthlyStats :one
SELECT
    COUNT(DISTINCT strftime('%Y-%m-%d', substr(watched_at, 1, 26))) AS days_with_views,
    COUNT(*) AS total_views_this_month,
    COUNT(DISTINCT video_id) AS unique_videos_watched
FROM watched_history
WHERE substr(watched_at, 1, 26) >= ?
  AND substr(watched_at, 1, 26) < ?
  AND watched_at IS NOT NULL
`

type GetMonthlyStatsParams struct {
	WatchedAt   sql.NullTime
	WatchedAt_2 sql.NullTime
}

type GetMonthlyStatsRow struct {
	DaysWithViews       int64
	TotalViewsThisMonth int64
	UniqueVideosWatched int64
}

func (q *Queries) GetMonthlyStats(ctx context.Context, arg GetMonthlyStatsParams) (GetMonthlyStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getMonthlyStats, arg.WatchedAt, arg.WatchedAt_2)
	var i GetMonthlyStatsRow
	err := row.Scan(&i.DaysWithViews, &i.TotalViewsThisMonth, &i.UniqueVideosWatched)
	return i, err
}

const getSeriesViews = `-- name: GetSeriesViews :many
SELECT
    COALESCE(s.id, 0) AS series_id,
    COALESCE(s.syobocal_title_name, 'No Series') AS series_name,
    SUM(v.views) AS total_views,
    COUNT(v.id) AS video_count
FROM video v
LEFT JOIN series s ON v.series_id = s.id
WHERE v.is_deleted = 0
GROUP BY v.series_id
ORDER BY total_views DESC
`

type GetSeriesViewsRow struct {
	SeriesID   int64
	SeriesName string
	TotalViews sql.NullFloat64
	VideoCount int64
}

func (q *Queries) GetSeriesViews(ctx context.Context) ([]GetSeriesViewsRow, error) {
	rows, err := q.db.QueryContext(ctx, getSeriesViews)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSeriesViewsRow
	for rows.Next() {
		var i GetSeriesViewsRow
		if err := rows.Scan(
			&i.SeriesID,
			&i.SeriesName,
			&i.TotalViews,
			&i.VideoCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVideoRanking = `-- name: GetVideoRanking :many
SELECT
    v.id,
    v.file_name,
    v.views,
    v.updated_at,
    s.syobocal_title_name AS series_name
FROM video v
LEFT JOIN series s ON v.series_id = s.id
WHERE v.is_deleted = 0
  AND v.views > 0
ORDER BY v.views DESC
LIMIT ?
`

type GetVideoRankingRow struct {
	ID         int64
	FileName   sql.NullString
	Views      sql.NullInt64
	UpdatedAt  sql.NullTime
	SeriesName sql.NullString
}

func (q *Queries) GetVideoRanking(ctx context.Context, limit int64) ([]GetVideoRankingRow, error) {
	rows, err := q.db.QueryContext(ctx, getVideoRanking, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetVideoRankingRow
	for rows.Next() {
		var i GetVideoRankingRow
		if err := rows.Scan(
			&i.ID,
			&i.FileName,
			&i.Views,
			&i.UpdatedAt,
			&i.SeriesName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWatchedHistoryByDate = `-- name: GetWatchedHistoryByDate :many
SELECT
    strftime('%Y-%m-%d', substr(watched_at, 1, 26)) AS date,
    COUNT(*) AS watch_count
FROM watched_history
WHERE substr(watched_at, 1, 26) >= ?
  AND substr(watched_at, 1, 26) < ?
  AND watched_at IS NOT NULL
GROUP BY strftime('%Y-%m-%d', substr(watched_at, 1, 26))
ORDER BY date DESC
`

type GetWatchedHistoryByDateParams struct {
	WatchedAt   sql.NullTime
	WatchedAt_2 sql.NullTime
}

type GetWatchedHistoryByDateRow struct {
	Date       interface{}
	WatchCount int64
}

func (q *Queries) GetWatchedHistoryByDate(ctx context.Context, arg GetWatchedHistoryByDateParams) ([]GetWatchedHistoryByDateRow, error) {
	rows, err := q.db.QueryContext(ctx, getWatchedHistoryByDate, arg.WatchedAt, arg.WatchedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetWatchedHistoryByDateRow
	for rows.Next() {
		var i GetWatchedHistoryByDateRow
		if err := rows.Scan(&i.Date, &i.WatchCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
