// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: capture.sql

package db

import (
	"context"
	"database/sql"
)

const countAllCaptures = `-- name: CountAllCaptures :one
SELECT COUNT(*) as count
FROM capture
`

func (q *Queries) CountAllCaptures(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAllCaptures)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCaptureListByVideo = `-- name: CountCaptureListByVideo :one
SELECT COUNT(*) as count
FROM capture
WHERE video_id = ?
`

func (q *Queries) CountCaptureListByVideo(ctx context.Context, videoID sql.NullInt64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCaptureListByVideo, videoID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCapture = `-- name: CreateCapture :exec
INSERT INTO capture (filename, video_id, save_dir, save_path, created_at, playback_position, comment_delay)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateCaptureParams struct {
	Filename         sql.NullString
	VideoID          sql.NullInt64
	SaveDir          sql.NullString
	SavePath         sql.NullString
	CreatedAt        sql.NullTime
	PlaybackPosition sql.NullFloat64
	CommentDelay     sql.NullFloat64
}

func (q *Queries) CreateCapture(ctx context.Context, arg CreateCaptureParams) error {
	_, err := q.db.ExecContext(ctx, createCapture,
		arg.Filename,
		arg.VideoID,
		arg.SaveDir,
		arg.SavePath,
		arg.CreatedAt,
		arg.PlaybackPosition,
		arg.CommentDelay,
	)
	return err
}

const deleteCapture = `-- name: DeleteCapture :exec
DELETE FROM capture
WHERE id = ?
`

func (q *Queries) DeleteCapture(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCapture, id)
	return err
}

const getAllCaptures = `-- name: GetAllCaptures :many
SELECT id, filename, video_id, save_dir, save_path, created_at, playback_position, comment_delay
FROM capture
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type GetAllCapturesParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) GetAllCaptures(ctx context.Context, arg GetAllCapturesParams) ([]Capture, error) {
	rows, err := q.db.QueryContext(ctx, getAllCaptures, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Capture
	for rows.Next() {
		var i Capture
		if err := rows.Scan(
			&i.ID,
			&i.Filename,
			&i.VideoID,
			&i.SaveDir,
			&i.SavePath,
			&i.CreatedAt,
			&i.PlaybackPosition,
			&i.CommentDelay,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCaptureByID = `-- name: GetCaptureByID :one
SELECT id, filename, video_id, save_dir, save_path, created_at, playback_position, comment_delay
FROM capture
WHERE id = ?
`

func (q *Queries) GetCaptureByID(ctx context.Context, id int64) (Capture, error) {
	row := q.db.QueryRowContext(ctx, getCaptureByID, id)
	var i Capture
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.VideoID,
		&i.SaveDir,
		&i.SavePath,
		&i.CreatedAt,
		&i.PlaybackPosition,
		&i.CommentDelay,
	)
	return i, err
}

const getCaptureListByVideo = `-- name: GetCaptureListByVideo :many
SELECT id, filename, video_id, save_dir, save_path, created_at, playback_position, comment_delay
FROM capture
WHERE video_id = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type GetCaptureListByVideoParams struct {
	VideoID sql.NullInt64
	Limit   int64
	Offset  int64
}

func (q *Queries) GetCaptureListByVideo(ctx context.Context, arg GetCaptureListByVideoParams) ([]Capture, error) {
	rows, err := q.db.QueryContext(ctx, getCaptureListByVideo, arg.VideoID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Capture
	for rows.Next() {
		var i Capture
		if err := rows.Scan(
			&i.ID,
			&i.Filename,
			&i.VideoID,
			&i.SaveDir,
			&i.SavePath,
			&i.CreatedAt,
			&i.PlaybackPosition,
			&i.CommentDelay,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCapture = `-- name: UpdateCapture :exec
UPDATE capture
SET filename = ?, video_id = ?, save_dir = ?, save_path = ?, playback_position = ?, comment_delay = ?
WHERE id = ?
`

type UpdateCaptureParams struct {
	Filename         sql.NullString
	VideoID          sql.NullInt64
	SaveDir          sql.NullString
	SavePath         sql.NullString
	PlaybackPosition sql.NullFloat64
	CommentDelay     sql.NullFloat64
	ID               int64
}

func (q *Queries) UpdateCapture(ctx context.Context, arg UpdateCaptureParams) error {
	_, err := q.db.ExecContext(ctx, updateCapture,
		arg.Filename,
		arg.VideoID,
		arg.SaveDir,
		arg.SavePath,
		arg.PlaybackPosition,
		arg.CommentDelay,
		arg.ID,
	)
	return err
}
