// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"encoding/json"
)

type Capture struct {
	ID               int64
	Filename         sql.NullString
	VideoID          sql.NullInt64
	SaveDir          sql.NullString
	SavePath         sql.NullString
	CreatedAt        sql.NullTime
	PlaybackPosition sql.NullFloat64
	CommentDelay     sql.NullFloat64
}

type Folder struct {
	ID        int64
	Path      sql.NullString
	IsWatched sql.NullFloat64
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Series struct {
	ID                  int64
	SeriesNameFile      sql.NullString
	SyobocalTitleID     sql.NullInt64
	SyobocalTitleName   sql.NullString
	SyobocalTitleNameEn sql.NullString
	Comment             json.RawMessage
	FirstYear           sql.NullInt64
	FirstMonth          sql.NullInt64
	FirstEndYear        sql.NullInt64
	FirstEndMonth       sql.NullInt64
	Subtitles           json.RawMessage
	CreatedAt           sql.NullTime
	UpdatedAt           sql.NullTime
}

type User struct {
	ID                   int64
	Name                 sql.NullString
	Password             sql.NullString
	IsAdmin              sql.NullInt64
	ClientSettingsJson   json.RawMessage
	NiconicoUserID       sql.NullInt64
	NiconicoUserName     sql.NullString
	NiconicoUserPremium  sql.NullInt64
	NiconicoAccessToken  sql.NullString
	NiconicoRefreshToken sql.NullString
	CreatedAt            sql.NullTime
	UpdatedAt            sql.NullTime
}

type Video struct {
	ID                 int64
	FileName           sql.NullString
	FolderID           sql.NullInt64
	SeriesID           sql.NullInt64
	Episode            sql.NullInt64
	Subtitle           sql.NullString
	FilePath           sql.NullString
	Description        sql.NullString
	Status             sql.NullString
	FileHash           sql.NullString
	FileSize           sql.NullInt64
	JikkyoCommentCount sql.NullInt64
	JikkyoDate         sql.NullTime
	Views              sql.NullInt64
	Liked              sql.NullFloat64
	ScreenshotFilePath sql.NullString
	Duration           sql.NullFloat64
	ThumbnailInfoJson  json.RawMessage
	ChannelID          sql.NullInt64
	ProgStartTime      sql.NullTime
	ProgEndTime        sql.NullTime
	IsDeleted          sql.NullFloat64
	CreatedAt          sql.NullTime
	UpdatedAt          sql.NullTime
}

type WatchedHistory struct {
	ID        int64
	VideoID   int64
	WatchedAt sql.NullTime
}
