// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CountAllCaptures(ctx context.Context) (int64, error)
	CountCaptureListByVideo(ctx context.Context, videoID sql.NullInt64) (int64, error)
	CountSearchVideos(ctx context.Context, arg CountSearchVideosParams) (int64, error)
	CountSearchVideosNoFilter(ctx context.Context, arg CountSearchVideosNoFilterParams) (int64, error)
	CountVideoListByStatus(ctx context.Context, status sql.NullString) (int64, error)
	CountVideoListByYear(ctx context.Context, jikkyoDate sql.NullTime) (int64, error)
	CountWatchedHistoryByVideoID(ctx context.Context, videoID int64) (int64, error)
	CreateCapture(ctx context.Context, arg CreateCaptureParams) error
	CreateSeries(ctx context.Context, arg CreateSeriesParams) error
	CreateWatchedHistory(ctx context.Context, arg CreateWatchedHistoryParams) error
	DeleteCapture(ctx context.Context, id int64) error
	DeleteSeries(ctx context.Context, id int64) error
	DeleteWatchedHistoryByVideoID(ctx context.Context, videoID int64) error
	GetAllCaptures(ctx context.Context, arg GetAllCapturesParams) ([]Capture, error)
	GetAllCapturesCreatedAtAsc(ctx context.Context, arg GetAllCapturesCreatedAtAscParams) ([]Capture, error)
	GetAllCapturesIdAsc(ctx context.Context, arg GetAllCapturesIdAscParams) ([]Capture, error)
	GetAllCapturesIdDesc(ctx context.Context, arg GetAllCapturesIdDescParams) ([]Capture, error)
	GetAllSeries(ctx context.Context) ([]Series, error)
	GetAllSeriesWithCount(ctx context.Context) ([]GetAllSeriesWithCountRow, error)
	GetCaptureByID(ctx context.Context, id int64) (Capture, error)
	GetCaptureListByVideo(ctx context.Context, arg GetCaptureListByVideoParams) ([]Capture, error)
	GetCaptureListByVideoCreatedAtAsc(ctx context.Context, arg GetCaptureListByVideoCreatedAtAscParams) ([]Capture, error)
	GetCaptureListByVideoIdAsc(ctx context.Context, arg GetCaptureListByVideoIdAscParams) ([]Capture, error)
	GetCaptureListByVideoIdDesc(ctx context.Context, arg GetCaptureListByVideoIdDescParams) ([]Capture, error)
	GetDailyViews(ctx context.Context, arg GetDailyViewsParams) ([]GetDailyViewsRow, error)
	GetDailyViewsWithDetails(ctx context.Context, arg GetDailyViewsWithDetailsParams) ([]GetDailyViewsWithDetailsRow, error)
	GetMonthlyStats(ctx context.Context, arg GetMonthlyStatsParams) (GetMonthlyStatsRow, error)
	GetRecentWatchedHistory(ctx context.Context, arg GetRecentWatchedHistoryParams) ([]WatchedHistory, error)
	GetRecentWatchedHistoryWithin1Hour(ctx context.Context, videoID int64) (int64, error)
	GetSeriesByID(ctx context.Context, id int64) (Series, error)
	GetSeriesByName(ctx context.Context, seriesNameFile sql.NullString) (Series, error)
	GetSeriesViews(ctx context.Context, arg GetSeriesViewsParams) ([]GetSeriesViewsRow, error)
	GetVideoByID(ctx context.Context, id int64) (Video, error)
	GetVideoListByStatus(ctx context.Context, arg GetVideoListByStatusParams) ([]Video, error)
	GetVideoListByYear(ctx context.Context, arg GetVideoListByYearParams) ([]Video, error)
	GetVideoRanking(ctx context.Context, limit int64) ([]GetVideoRankingRow, error)
	GetVideoYears(ctx context.Context) ([]int64, error)
	GetVideosForSeries(ctx context.Context, seriesID sql.NullInt64) ([]Video, error)
	GetWatchedHistoryByDate(ctx context.Context, arg GetWatchedHistoryByDateParams) ([]GetWatchedHistoryByDateRow, error)
	GetWatchedHistoryByVideoID(ctx context.Context, arg GetWatchedHistoryByVideoIDParams) ([]WatchedHistory, error)
	IncrementVideoViews(ctx context.Context, arg IncrementVideoViewsParams) error
	SearchVideos(ctx context.Context, arg SearchVideosParams) ([]Video, error)
	SearchVideosNoFilter(ctx context.Context, arg SearchVideosNoFilterParams) ([]Video, error)
	UpdateCapture(ctx context.Context, arg UpdateCaptureParams) error
	UpdateSeries(ctx context.Context, arg UpdateSeriesParams) error
	UpdateVideoJikkyoMetadata(ctx context.Context, arg UpdateVideoJikkyoMetadataParams) error
}

var _ Querier = (*Queries)(nil)
