// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CountAllCaptures(ctx context.Context) (int64, error)
	CountCaptureListByVideo(ctx context.Context, videoID sql.NullInt64) (int64, error)
	CountSearchVideos(ctx context.Context, arg CountSearchVideosParams) (int64, error)
	CountSearchVideosNoFilter(ctx context.Context, arg CountSearchVideosNoFilterParams) (int64, error)
	CountVideoListByStatus(ctx context.Context, status sql.NullString) (int64, error)
	CountVideoListByYear(ctx context.Context, jikkyoDate sql.NullTime) (int64, error)
	CreateCapture(ctx context.Context, arg CreateCaptureParams) error
	CreateSeries(ctx context.Context, arg CreateSeriesParams) error
	DeleteCapture(ctx context.Context, id int64) error
	DeleteSeries(ctx context.Context, id int64) error
	GetAllCaptures(ctx context.Context, arg GetAllCapturesParams) ([]Capture, error)
	GetAllSeries(ctx context.Context) ([]Series, error)
	GetAllSeriesWithCount(ctx context.Context) ([]GetAllSeriesWithCountRow, error)
	GetCaptureByID(ctx context.Context, id int64) (Capture, error)
	GetCaptureListByVideo(ctx context.Context, arg GetCaptureListByVideoParams) ([]Capture, error)
	GetSeriesByID(ctx context.Context, id int64) (Series, error)
	GetSeriesByName(ctx context.Context, seriesNameFile sql.NullString) (Series, error)
	GetVideoByID(ctx context.Context, id int64) (Video, error)
	GetVideoListByStatus(ctx context.Context, arg GetVideoListByStatusParams) ([]Video, error)
	GetVideoListByYear(ctx context.Context, arg GetVideoListByYearParams) ([]Video, error)
	GetVideoYears(ctx context.Context) ([]int64, error)
	GetVideosForSeries(ctx context.Context, seriesID sql.NullInt64) ([]Video, error)
	SearchVideos(ctx context.Context, arg SearchVideosParams) ([]Video, error)
	SearchVideosNoFilter(ctx context.Context, arg SearchVideosNoFilterParams) ([]Video, error)
	UpdateCapture(ctx context.Context, arg UpdateCaptureParams) error
	UpdateSeries(ctx context.Context, arg UpdateSeriesParams) error
}

var _ Querier = (*Queries)(nil)
