// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: series.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
)

const createSeries = `-- name: CreateSeries :exec
INSERT INTO series (series_name_file, syobocal_title_id, syobocal_title_name, syobocal_title_name_en, comment, first_year, first_month, first_end_year, first_end_month, subtitles, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateSeriesParams struct {
	SeriesNameFile      sql.NullString
	SyobocalTitleID     sql.NullInt64
	SyobocalTitleName   sql.NullString
	SyobocalTitleNameEn sql.NullString
	Comment             json.RawMessage
	FirstYear           sql.NullInt64
	FirstMonth          sql.NullInt64
	FirstEndYear        sql.NullInt64
	FirstEndMonth       sql.NullInt64
	Subtitles           json.RawMessage
	CreatedAt           sql.NullTime
	UpdatedAt           sql.NullTime
}

func (q *Queries) CreateSeries(ctx context.Context, arg CreateSeriesParams) error {
	_, err := q.db.ExecContext(ctx, createSeries,
		arg.SeriesNameFile,
		arg.SyobocalTitleID,
		arg.SyobocalTitleName,
		arg.SyobocalTitleNameEn,
		arg.Comment,
		arg.FirstYear,
		arg.FirstMonth,
		arg.FirstEndYear,
		arg.FirstEndMonth,
		arg.Subtitles,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteSeries = `-- name: DeleteSeries :exec
DELETE FROM series
WHERE id = ?
`

func (q *Queries) DeleteSeries(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteSeries, id)
	return err
}

const getAllSeries = `-- name: GetAllSeries :many
SELECT id, series_name_file, syobocal_title_id, syobocal_title_name, syobocal_title_name_en, comment, first_year, first_month, first_end_year, first_end_month, subtitles, created_at, updated_at
FROM series
ORDER BY series_name_file ASC
`

func (q *Queries) GetAllSeries(ctx context.Context) ([]Series, error) {
	rows, err := q.db.QueryContext(ctx, getAllSeries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Series
	for rows.Next() {
		var i Series
		if err := rows.Scan(
			&i.ID,
			&i.SeriesNameFile,
			&i.SyobocalTitleID,
			&i.SyobocalTitleName,
			&i.SyobocalTitleNameEn,
			&i.Comment,
			&i.FirstYear,
			&i.FirstMonth,
			&i.FirstEndYear,
			&i.FirstEndMonth,
			&i.Subtitles,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllSeriesWithCount = `-- name: GetAllSeriesWithCount :many
SELECT s.id, s.series_name_file, s.syobocal_title_id, s.syobocal_title_name, s.syobocal_title_name_en, s.comment, s.first_year, s.first_month, s.first_end_year, s.first_end_month, s.subtitles, s.created_at, s.updated_at, COUNT(v.id) as video_count
FROM series s
LEFT JOIN video v ON s.id = v.series_id AND v.is_deleted = 0
GROUP BY s.id
ORDER BY s.series_name_file ASC
`

type GetAllSeriesWithCountRow struct {
	ID                  int64
	SeriesNameFile      sql.NullString
	SyobocalTitleID     sql.NullInt64
	SyobocalTitleName   sql.NullString
	SyobocalTitleNameEn sql.NullString
	Comment             json.RawMessage
	FirstYear           sql.NullInt64
	FirstMonth          sql.NullInt64
	FirstEndYear        sql.NullInt64
	FirstEndMonth       sql.NullInt64
	Subtitles           json.RawMessage
	CreatedAt           sql.NullTime
	UpdatedAt           sql.NullTime
	VideoCount          int64
}

func (q *Queries) GetAllSeriesWithCount(ctx context.Context) ([]GetAllSeriesWithCountRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllSeriesWithCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllSeriesWithCountRow
	for rows.Next() {
		var i GetAllSeriesWithCountRow
		if err := rows.Scan(
			&i.ID,
			&i.SeriesNameFile,
			&i.SyobocalTitleID,
			&i.SyobocalTitleName,
			&i.SyobocalTitleNameEn,
			&i.Comment,
			&i.FirstYear,
			&i.FirstMonth,
			&i.FirstEndYear,
			&i.FirstEndMonth,
			&i.Subtitles,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VideoCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSeriesByID = `-- name: GetSeriesByID :one
SELECT id, series_name_file, syobocal_title_id, syobocal_title_name, syobocal_title_name_en, comment, first_year, first_month, first_end_year, first_end_month, subtitles, created_at, updated_at
FROM series
WHERE id = ?
`

func (q *Queries) GetSeriesByID(ctx context.Context, id int64) (Series, error) {
	row := q.db.QueryRowContext(ctx, getSeriesByID, id)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.SeriesNameFile,
		&i.SyobocalTitleID,
		&i.SyobocalTitleName,
		&i.SyobocalTitleNameEn,
		&i.Comment,
		&i.FirstYear,
		&i.FirstMonth,
		&i.FirstEndYear,
		&i.FirstEndMonth,
		&i.Subtitles,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSeriesByName = `-- name: GetSeriesByName :one
SELECT id, series_name_file, syobocal_title_id, syobocal_title_name, syobocal_title_name_en, comment, first_year, first_month, first_end_year, first_end_month, subtitles, created_at, updated_at
FROM series
WHERE series_name_file = ?
`

func (q *Queries) GetSeriesByName(ctx context.Context, seriesNameFile sql.NullString) (Series, error) {
	row := q.db.QueryRowContext(ctx, getSeriesByName, seriesNameFile)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.SeriesNameFile,
		&i.SyobocalTitleID,
		&i.SyobocalTitleName,
		&i.SyobocalTitleNameEn,
		&i.Comment,
		&i.FirstYear,
		&i.FirstMonth,
		&i.FirstEndYear,
		&i.FirstEndMonth,
		&i.Subtitles,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSeries = `-- name: UpdateSeries :exec
UPDATE series
SET series_name_file = ?, syobocal_title_id = ?, syobocal_title_name = ?, syobocal_title_name_en = ?, comment = ?, first_year = ?, first_month = ?, first_end_year = ?, first_end_month = ?, subtitles = ?, updated_at = ?
WHERE id = ?
`

type UpdateSeriesParams struct {
	SeriesNameFile      sql.NullString
	SyobocalTitleID     sql.NullInt64
	SyobocalTitleName   sql.NullString
	SyobocalTitleNameEn sql.NullString
	Comment             json.RawMessage
	FirstYear           sql.NullInt64
	FirstMonth          sql.NullInt64
	FirstEndYear        sql.NullInt64
	FirstEndMonth       sql.NullInt64
	Subtitles           json.RawMessage
	UpdatedAt           sql.NullTime
	ID                  int64
}

func (q *Queries) UpdateSeries(ctx context.Context, arg UpdateSeriesParams) error {
	_, err := q.db.ExecContext(ctx, updateSeries,
		arg.SeriesNameFile,
		arg.SyobocalTitleID,
		arg.SyobocalTitleName,
		arg.SyobocalTitleNameEn,
		arg.Comment,
		arg.FirstYear,
		arg.FirstMonth,
		arg.FirstEndYear,
		arg.FirstEndMonth,
		arg.Subtitles,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
