// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: video.sql

package db

import (
	"context"
	"database/sql"
)

const countSearchVideos = `-- name: CountSearchVideos :one
SELECT COUNT(*) as count
FROM video v
LEFT JOIN series s ON v.series_id = s.id
WHERE (v.file_name LIKE ?
       OR v.description LIKE ?
       OR s.syobocal_title_name LIKE ?
       OR v.subtitle LIKE ?)
  AND v.status = ?
`

type CountSearchVideosParams struct {
	FileName          sql.NullString
	Description       sql.NullString
	SyobocalTitleName sql.NullString
	Subtitle          sql.NullString
	Status            sql.NullString
}

func (q *Queries) CountSearchVideos(ctx context.Context, arg CountSearchVideosParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSearchVideos,
		arg.FileName,
		arg.Description,
		arg.SyobocalTitleName,
		arg.Subtitle,
		arg.Status,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSearchVideosNoFilter = `-- name: CountSearchVideosNoFilter :one
SELECT COUNT(*) as count
FROM video v
LEFT JOIN series s ON v.series_id = s.id
WHERE (v.file_name LIKE ?
       OR v.description LIKE ?
       OR s.syobocal_title_name LIKE ?
       OR v.subtitle LIKE ?)
`

type CountSearchVideosNoFilterParams struct {
	FileName          sql.NullString
	Description       sql.NullString
	SyobocalTitleName sql.NullString
	Subtitle          sql.NullString
}

func (q *Queries) CountSearchVideosNoFilter(ctx context.Context, arg CountSearchVideosNoFilterParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSearchVideosNoFilter,
		arg.FileName,
		arg.Description,
		arg.SyobocalTitleName,
		arg.Subtitle,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countVideoListByStatus = `-- name: CountVideoListByStatus :one
SELECT COUNT(*) as count
FROM video
WHERE is_deleted = 0 AND status = ?
`

func (q *Queries) CountVideoListByStatus(ctx context.Context, status sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, countVideoListByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countVideoListByYear = `-- name: CountVideoListByYear :one
SELECT COUNT(*) as count
FROM video
WHERE is_deleted = 0 AND CAST(SUBSTR(jikkyo_date, 1, 4) AS INTEGER) = ?
`

func (q *Queries) CountVideoListByYear(ctx context.Context, jikkyoDate sql.NullTime) (int64, error) {
	row := q.db.QueryRowContext(ctx, countVideoListByYear, jikkyoDate)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getVideoByID = `-- name: GetVideoByID :one
SELECT id, file_name, folder_id, series_id, episode, subtitle, file_path, description, status, file_hash, file_size, jikkyo_comment_count, jikkyo_date, views, liked, screenshot_file_path, duration, thumbnail_info_json, channel_id, prog_start_time, prog_end_time, is_deleted, created_at, updated_at
FROM video
WHERE id = ?
`

func (q *Queries) GetVideoByID(ctx context.Context, id int64) (Video, error) {
	row := q.db.QueryRowContext(ctx, getVideoByID, id)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.FileName,
		&i.FolderID,
		&i.SeriesID,
		&i.Episode,
		&i.Subtitle,
		&i.FilePath,
		&i.Description,
		&i.Status,
		&i.FileHash,
		&i.FileSize,
		&i.JikkyoCommentCount,
		&i.JikkyoDate,
		&i.Views,
		&i.Liked,
		&i.ScreenshotFilePath,
		&i.Duration,
		&i.ThumbnailInfoJson,
		&i.ChannelID,
		&i.ProgStartTime,
		&i.ProgEndTime,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVideoListByStatus = `-- name: GetVideoListByStatus :many
SELECT id, file_name, folder_id, series_id, episode, subtitle, file_path, description, status, file_hash, file_size, jikkyo_comment_count, jikkyo_date, views, liked, screenshot_file_path, duration, thumbnail_info_json, channel_id, prog_start_time, prog_end_time, is_deleted, created_at, updated_at
FROM video
WHERE is_deleted = 0 AND status = ?
ORDER BY jikkyo_date DESC
LIMIT ? OFFSET ?
`

type GetVideoListByStatusParams struct {
	Status sql.NullString
	Limit  int64
	Offset int64
}

func (q *Queries) GetVideoListByStatus(ctx context.Context, arg GetVideoListByStatusParams) ([]Video, error) {
	rows, err := q.db.QueryContext(ctx, getVideoListByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.FileName,
			&i.FolderID,
			&i.SeriesID,
			&i.Episode,
			&i.Subtitle,
			&i.FilePath,
			&i.Description,
			&i.Status,
			&i.FileHash,
			&i.FileSize,
			&i.JikkyoCommentCount,
			&i.JikkyoDate,
			&i.Views,
			&i.Liked,
			&i.ScreenshotFilePath,
			&i.Duration,
			&i.ThumbnailInfoJson,
			&i.ChannelID,
			&i.ProgStartTime,
			&i.ProgEndTime,
			&i.IsDeleted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVideoListByYear = `-- name: GetVideoListByYear :many
SELECT id, file_name, folder_id, series_id, episode, subtitle, file_path, description, status, file_hash, file_size, jikkyo_comment_count, jikkyo_date, views, liked, screenshot_file_path, duration, thumbnail_info_json, channel_id, prog_start_time, prog_end_time, is_deleted, created_at, updated_at
FROM video
WHERE is_deleted = 0 AND CAST(SUBSTR(jikkyo_date, 1, 4) AS INTEGER) = ?
ORDER BY jikkyo_date DESC
LIMIT ? OFFSET ?
`

type GetVideoListByYearParams struct {
	JikkyoDate sql.NullTime
	Limit      int64
	Offset     int64
}

func (q *Queries) GetVideoListByYear(ctx context.Context, arg GetVideoListByYearParams) ([]Video, error) {
	rows, err := q.db.QueryContext(ctx, getVideoListByYear, arg.JikkyoDate, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.FileName,
			&i.FolderID,
			&i.SeriesID,
			&i.Episode,
			&i.Subtitle,
			&i.FilePath,
			&i.Description,
			&i.Status,
			&i.FileHash,
			&i.FileSize,
			&i.JikkyoCommentCount,
			&i.JikkyoDate,
			&i.Views,
			&i.Liked,
			&i.ScreenshotFilePath,
			&i.Duration,
			&i.ThumbnailInfoJson,
			&i.ChannelID,
			&i.ProgStartTime,
			&i.ProgEndTime,
			&i.IsDeleted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVideoYears = `-- name: GetVideoYears :many
SELECT DISTINCT CAST(SUBSTR(jikkyo_date, 1, 4) AS INTEGER) as year
FROM video
WHERE is_deleted = 0
AND jikkyo_date IS NOT NULL
ORDER BY year DESC
`

func (q *Queries) GetVideoYears(ctx context.Context) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, getVideoYears)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var year int64
		if err := rows.Scan(&year); err != nil {
			return nil, err
		}
		items = append(items, year)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVideosForSeries = `-- name: GetVideosForSeries :many
SELECT id, file_name, folder_id, series_id, episode, subtitle, file_path, description, status, file_hash, file_size, jikkyo_comment_count, jikkyo_date, views, liked, screenshot_file_path, duration, thumbnail_info_json, channel_id, prog_start_time, prog_end_time, is_deleted, created_at, updated_at
FROM video
WHERE series_id = ? AND is_deleted = 0
ORDER BY file_name ASC
`

func (q *Queries) GetVideosForSeries(ctx context.Context, seriesID sql.NullInt64) ([]Video, error) {
	rows, err := q.db.QueryContext(ctx, getVideosForSeries, seriesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.FileName,
			&i.FolderID,
			&i.SeriesID,
			&i.Episode,
			&i.Subtitle,
			&i.FilePath,
			&i.Description,
			&i.Status,
			&i.FileHash,
			&i.FileSize,
			&i.JikkyoCommentCount,
			&i.JikkyoDate,
			&i.Views,
			&i.Liked,
			&i.ScreenshotFilePath,
			&i.Duration,
			&i.ThumbnailInfoJson,
			&i.ChannelID,
			&i.ProgStartTime,
			&i.ProgEndTime,
			&i.IsDeleted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchVideos = `-- name: SearchVideos :many
SELECT v.id, v.file_name, v.folder_id, v.series_id, v.episode, v.subtitle, v.file_path, v.description, v.status, v.file_hash, v.file_size, v.jikkyo_comment_count, v.jikkyo_date, v.views, v.liked, v.screenshot_file_path, v.duration, v.thumbnail_info_json, v.channel_id, v.prog_start_time, v.prog_end_time, v.is_deleted, v.created_at, v.updated_at
FROM video v
LEFT JOIN series s ON v.series_id = s.id
WHERE (v.file_name LIKE ?
       OR v.description LIKE ?
       OR s.syobocal_title_name LIKE ?
       OR v.subtitle LIKE ?)
  AND v.status = ?
ORDER BY v.jikkyo_date DESC
LIMIT ? OFFSET ?
`

type SearchVideosParams struct {
	FileName          sql.NullString
	Description       sql.NullString
	SyobocalTitleName sql.NullString
	Subtitle          sql.NullString
	Status            sql.NullString
	Limit             int64
	Offset            int64
}

func (q *Queries) SearchVideos(ctx context.Context, arg SearchVideosParams) ([]Video, error) {
	rows, err := q.db.QueryContext(ctx, searchVideos,
		arg.FileName,
		arg.Description,
		arg.SyobocalTitleName,
		arg.Subtitle,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.FileName,
			&i.FolderID,
			&i.SeriesID,
			&i.Episode,
			&i.Subtitle,
			&i.FilePath,
			&i.Description,
			&i.Status,
			&i.FileHash,
			&i.FileSize,
			&i.JikkyoCommentCount,
			&i.JikkyoDate,
			&i.Views,
			&i.Liked,
			&i.ScreenshotFilePath,
			&i.Duration,
			&i.ThumbnailInfoJson,
			&i.ChannelID,
			&i.ProgStartTime,
			&i.ProgEndTime,
			&i.IsDeleted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchVideosNoFilter = `-- name: SearchVideosNoFilter :many
SELECT v.id, v.file_name, v.folder_id, v.series_id, v.episode, v.subtitle, v.file_path, v.description, v.status, v.file_hash, v.file_size, v.jikkyo_comment_count, v.jikkyo_date, v.views, v.liked, v.screenshot_file_path, v.duration, v.thumbnail_info_json, v.channel_id, v.prog_start_time, v.prog_end_time, v.is_deleted, v.created_at, v.updated_at
FROM video v
LEFT JOIN series s ON v.series_id = s.id
WHERE (v.file_name LIKE ?
       OR v.description LIKE ?
       OR s.syobocal_title_name LIKE ?
       OR v.subtitle LIKE ?)
ORDER BY v.jikkyo_date DESC
LIMIT ? OFFSET ?
`

type SearchVideosNoFilterParams struct {
	FileName          sql.NullString
	Description       sql.NullString
	SyobocalTitleName sql.NullString
	Subtitle          sql.NullString
	Limit             int64
	Offset            int64
}

func (q *Queries) SearchVideosNoFilter(ctx context.Context, arg SearchVideosNoFilterParams) ([]Video, error) {
	rows, err := q.db.QueryContext(ctx, searchVideosNoFilter,
		arg.FileName,
		arg.Description,
		arg.SyobocalTitleName,
		arg.Subtitle,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.FileName,
			&i.FolderID,
			&i.SeriesID,
			&i.Episode,
			&i.Subtitle,
			&i.FilePath,
			&i.Description,
			&i.Status,
			&i.FileHash,
			&i.FileSize,
			&i.JikkyoCommentCount,
			&i.JikkyoDate,
			&i.Views,
			&i.Liked,
			&i.ScreenshotFilePath,
			&i.Duration,
			&i.ThumbnailInfoJson,
			&i.ChannelID,
			&i.ProgStartTime,
			&i.ProgEndTime,
			&i.IsDeleted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVideoJikkyoMetadata = `-- name: UpdateVideoJikkyoMetadata :exec
UPDATE video
SET jikkyo_comment_count = ?,
    jikkyo_date = ?,
    updated_at = ?
WHERE id = ?
`

type UpdateVideoJikkyoMetadataParams struct {
	JikkyoCommentCount sql.NullInt64
	JikkyoDate         sql.NullTime
	UpdatedAt          sql.NullTime
	ID                 int64
}

func (q *Queries) UpdateVideoJikkyoMetadata(ctx context.Context, arg UpdateVideoJikkyoMetadataParams) error {
	_, err := q.db.ExecContext(ctx, updateVideoJikkyoMetadata,
		arg.JikkyoCommentCount,
		arg.JikkyoDate,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
