// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: watched_history.sql

package db

import (
	"context"
	"database/sql"
)

const countWatchedHistoryByVideoID = `-- name: CountWatchedHistoryByVideoID :one
SELECT COUNT(*) as count
FROM watched_history
WHERE video_id = ?
`

func (q *Queries) CountWatchedHistoryByVideoID(ctx context.Context, videoID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWatchedHistoryByVideoID, videoID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWatchedHistory = `-- name: CreateWatchedHistory :exec
INSERT INTO watched_history (video_id, watched_at)
VALUES (?, ?)
`

type CreateWatchedHistoryParams struct {
	VideoID   int64
	WatchedAt sql.NullTime
}

func (q *Queries) CreateWatchedHistory(ctx context.Context, arg CreateWatchedHistoryParams) error {
	_, err := q.db.ExecContext(ctx, createWatchedHistory, arg.VideoID, arg.WatchedAt)
	return err
}

const deleteWatchedHistoryByVideoID = `-- name: DeleteWatchedHistoryByVideoID :exec
DELETE FROM watched_history
WHERE video_id = ?
`

func (q *Queries) DeleteWatchedHistoryByVideoID(ctx context.Context, videoID int64) error {
	_, err := q.db.ExecContext(ctx, deleteWatchedHistoryByVideoID, videoID)
	return err
}

const getRecentWatchedHistory = `-- name: GetRecentWatchedHistory :many
SELECT id, video_id, watched_at
FROM watched_history
ORDER BY watched_at DESC
LIMIT ? OFFSET ?
`

type GetRecentWatchedHistoryParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) GetRecentWatchedHistory(ctx context.Context, arg GetRecentWatchedHistoryParams) ([]WatchedHistory, error) {
	rows, err := q.db.QueryContext(ctx, getRecentWatchedHistory, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WatchedHistory
	for rows.Next() {
		var i WatchedHistory
		if err := rows.Scan(&i.ID, &i.VideoID, &i.WatchedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentWatchedHistoryWithin1Hour = `-- name: GetRecentWatchedHistoryWithin1Hour :one
SELECT id
FROM watched_history
WHERE video_id = ? 
  AND watched_at > datetime('now', '-1 hour', 'localtime')
ORDER BY watched_at DESC
LIMIT 1
`

func (q *Queries) GetRecentWatchedHistoryWithin1Hour(ctx context.Context, videoID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getRecentWatchedHistoryWithin1Hour, videoID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getWatchedHistoryByVideoID = `-- name: GetWatchedHistoryByVideoID :many
SELECT id, video_id, watched_at
FROM watched_history
WHERE video_id = ?
ORDER BY watched_at DESC
LIMIT ? OFFSET ?
`

type GetWatchedHistoryByVideoIDParams struct {
	VideoID int64
	Limit   int64
	Offset  int64
}

func (q *Queries) GetWatchedHistoryByVideoID(ctx context.Context, arg GetWatchedHistoryByVideoIDParams) ([]WatchedHistory, error) {
	rows, err := q.db.QueryContext(ctx, getWatchedHistoryByVideoID, arg.VideoID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WatchedHistory
	for rows.Next() {
		var i WatchedHistory
		if err := rows.Scan(&i.ID, &i.VideoID, &i.WatchedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
