@baseUrl = http://localhost:8000/api/v1

### 実装済み機能

### GET /folders
GET {{baseUrl}}/folders
Accept: application/json
Accept-Language: ja


### DELETE /folders/{id}
DELETE {{baseUrl}}/folders/1
Accept: application/json
Accept-Language: ja


### Windows経由
POST {{baseUrl}}/folders
Content-Type: application/json
Accept-Language: ja

{
  "path": "D:\\デスクトップ\\アニメ\\年別\\3\\15"
}


### Docker経由
POST {{baseUrl}}/folders
Content-Type: application/json
Accept-Language: ja

{
  "path": "/mnt/d/デスクトップ/アニメ/年別/3/15"
}


### mp4
http://localhost:8000/api/v1/files/1/hibi01.mp4


### jpg
localhost:8000/screenshots/zsBPJrEqtKbF3jM9.jpg

----------------------------------------------------

