@baseUrl = http://localhost:8000/api/v1

##実装済み機能

##  /videos
GET {{baseUrl}}/videos?page=1&limit=20
Accept: application/json
Accept-Language: ja


###
##  /videos
GET {{baseUrl}}/videos?page=1&limit=10&sort=created_at&order=desc
Accept: application/json
Accept-Language: en


###
##  /videos?filterBy=liked
GET {{baseUrl}}/videos?filterBy=liked&page=1&limit=20
Accept: application/json
Accept-Language: ja


###
##  /videos?ids=1&ids=2&ids=3
GET {{baseUrl}}/videos?ids=1&ids=2&ids=3&page=1&limit=20
Accept: application/json
Accept-Language: ja


###
##  /videos/{id}
GET {{baseUrl}}/videos/1
Accept: application/json
Accept-Language: ja

----------------------------------------------------

### 
##  /videos/search
GET {{baseUrl}}/videos/search?q=test&page=1&limit=20
Accept: application/json
Accept-Language: ja


### 
## /videos/search
GET {{baseUrl}}/videos/search?q=test%20video&page=1&limit=20&order=desc
Accept: application/json
Accept-Language: ja


###
##  /videos/{id}/download
GET {{baseUrl}}/videos/1/download
Accept: application/json
Accept-Language: ja


###
## /videos/{id}/thumbnail/regenerate
POST {{baseUrl}}/videos/1/thumbnail/regenerate
Content-Type: application/json
Accept-Language: ja

{
  "timestamp": 10.5
}
